#!/bin/bash

# Script is used to build ansible host file for RH OSP overcloud nodes
# this should be executed from undercloud node as stack user
# copy output of this script to /etc/ansible/hosts

source ~/stackrc

nova=`openstack server list`
unique=`echo "$nova" | grep ctlplane | awk {' print $4 '} | sed 's/^[^-]*-//g' | sed 's/-.*//g' | sort | uniq`

echo "[all:vars]"
echo "ansible_ssh_user=heat-admin"

for i in $unique
        do
                echo "" 
                echo "[$i]"
                count=`echo "$nova" | grep ctlplane | grep $i | awk {' print $12 '} | sed 's/ctlplane=//g'| wc -l`
                for j in `eval echo {1..$count}`
                        do
                                ip=`echo "$nova" | grep ctlplane | grep $i | awk {' print $8 '} | sed 's/ctlplane=//g'| head -n $j | tail -n 1`
                                hostname=`echo "$nova" | grep ctlplane | grep $i | awk {' print $4 '} | head -n $j | tail -n 1`
                                echo "$hostname ansible_ssh_host=$ip" 
                        done
        done
